### ISSUE TITLE
Time Selectors close off too quickly - not able to select the time

### ISSUE THREAD

**Issue by odiechoo** [stanus74/saj-h2-lovelace-card#2]
When selecting the start and end times for charging and discharging, the Time Selectors automatically closes off too quickly that when we mouse up to select the time, it closes. Therefore, was unable to efectively use the Time Selector to choose the time.

**Comment by stanus74** [comment]
fixed in new version 1.0.2

Fix: Improved time selection dropdowns in Chrome 

- Fixes issue where time selection dropdowns close too quickly in Chrome 
- Ensures consistent dropdown background rendering in dark mode across all browsers
- Enhances usability with more stable dropdown interaction

**Comment by stanus74** [comment]
![Image](https://github.com/user-attachments/assets/25884be2-c3b1-4a13-af28-d9395d919adc)

go in Browser to Developer Mode F12

see in screenshot the settings to avoid file load from cache

![Image](https://github.com/user-attachments/assets/e62ea13c-2d16-4fa3-a7e6-7bdb9a52bf58)

**Comment by odiechoo** [comment]
I'm still having the same problem with the Time Selectors for v1.0.2

**Comment by stanus74** [comment]
use developer mode
deactivate cache see screenshot above
check if version 1.0.2 is actually loaded

![Image](https://github.com/user-attachments/assets/b26f948b-ea1a-46ce-8310-ab1161eb5f1f)

**Comment by odiechoo** [comment]
yes, v 1.0.2 is loaded.

![Image](https://github.com/user-attachments/assets/6df13bf0-fed9-4d4b-a66c-cd9a22da99bd)

**Comment by stanus74** [comment]
please explain in more detail

**Comment by odiechoo** [comment]
I'm hoping this video will upload and show you.

https://github.com/user-attachments/assets/e1dded26-1ede-497c-9f03-f4cefb69622c

**Comment by bierma1966** [comment]
Try an other Browser.
I use Opera and the dropdown Menü close also fast, but not so fast as by you.

**Comment by odiechoo** [comment]
The point is that it should stay until a time is selected or the mouse clicks elsewhere. It should not be auto-closing on its own, whether fast or slow.

**Comment by stanus74** [comment]
new version is online

**Comment by odiechoo** [comment]
Hi Stanus74, thanks for the quick turnaround. Its still similar though. Video as follows:

https://github.com/user-attachments/assets/757a7e73-65e2-461d-87b9-a94df8623caa

**Comment by stanus74** [comment]
all versions in firefox and chrome worked for me

i have made a new version with manual time entry

**Comment by stanus74** [comment]
new improve version is online v1.1.0

**Comment by odiechoo** [comment]
Firefox is interesting. It wouldn't even let me scroll down to the card and keeps jumping back up. Could be a clue?

I'll use the new version for now.

https://github.com/user-attachments/assets/f92c9d52-5123-4a37-b011-32635fdc4c0a

**Comment by odiechoo** [comment]
New version - The mouse selection doesn't really stay long enough for me to move over to the keyboard to type a number into the field.

![Image](https://github.com/user-attachments/assets/92d36ebe-4bd0-4751-8175-aebc55d07ef5)

https://github.com/user-attachments/assets/1dfbd80a-61a3-48c9-a0ba-945552255022

**Comment by stanus74** [comment]
improve version online v1.1.0
